version: '2'
services:
  app:
    container_name: app-cuac
    image: devscola/culturaaccesible:latest
    ports:
      - "8100:8100"
      - "35729:35729"
    volumes:
      - .:/opt/app
    command: bash -c "cd /opt/app/culturaaccesible && npm install && ionic serve --all"
